module.exports = {
  name: "amongUs",
  category:"Games",
  code: `$title[Among Us]
    $description[Among Us is a 2018 online multiplayer social deduction game developed and published by American game studio Innersloth. It was released on iOS and Android devices in June 2018 and on Windows in November 2018, featuring cross-platform play between these platforms. The game was also ported for the Nintendo Switch in December 2020, and has planned releases for the PlayStation 4, PlayStation 5, Xbox One and Xbox Series X/S in 2021. The game was inspired by the party game Mafia and the science fiction horror film The Thing, and since the release of its first map, The Skeld, three other maps were added, those being MIRA HQ, Polus and The Airship. The Airship's design is based on Infiltrating the Airship from the Henry Stickmin series, another video game series developed by Innersloth. A fifth map is currently in development and will be released in a future update.

The game takes place in a space-themed setting, in which players each take on one of two roles, most being Crewmates, and a predetermined number being Impostors. The goal of the Crewmates are to identify the Impostors, eliminate them, and complete tasks around the map; the Impostors' goal is to covertly sabotage and kill the Crewmates before they complete all of their tasks. Players suspected to be Impostors may be eliminated via a plurality vote, which any player may initiate by calling an emergency meeting (except during a crisis) or reporting a dead body. Crewmates win if all Impostors are ejected or all tasks are completed, whereas Impostors win if there is an equal number of Impostors and Crewmates, or if a critical sabotage goes unresolved.

While the game was initially released in 2018 to little mainstream attention, it received a massive influx of popularity in 2020 due to many well-known Twitch streamers and YouTubers playing it. The COVID-19 pandemic has also been credited to the growth of the game. The game received positive reviews from critics, being praised for its gameplay and setting, although it was criticized for its technical issues. In response to the game's popularity, Among Us 2 was announced in August 2020. However, the planned sequel was canceled a month later, and the team shifted its focus to improving the original game. Merchandise based on the game, such as toys, shirts, etc., were announced and released. Among Us has also inspired internet memes and achieved a very large following online.
For more information visit https://en.wikipedia.org/wiki/Among_Us
]
$color[#206694]
  `
}